version: '2'
services:
    huawei_saas-app:
        image: huawei_saas
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://huawei_saas-mysql:3306/huawei_saas?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    huawei_saas-mysql:
        extends:
            file: mysql.yml
            service: huawei_saas-mysql
